
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Aug 29 23:19:57 CEST 2017
//----------------------------------------------------

package mm120119;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREQUAL = 20;
  public static final int INCREMENT = 23;
  public static final int CONST = 8;
  public static final int CHAR = 5;
  public static final int NOTEQUAL = 36;
  public static final int SEMI = 48;
  public static final int LPAREN = 27;
  public static final int GREATER = 19;
  public static final int CONTINUE = 9;
  public static final int LESS = 25;
  public static final int FOR = 18;
  public static final int MINUS = 29;
  public static final int DECREMENT = 10;
  public static final int STATIC = 49;
  public static final int RPAREN = 46;
  public static final int AND = 2;
  public static final int LESSEQUAL = 26;
  public static final int OR = 38;
  public static final int BOOL = 3;
  public static final int CLASS = 6;
  public static final int EQUALEQUAL = 17;
  public static final int DIV = 11;
  public static final int DIVEQUAL = 12;
  public static final int PLUS = 39;
  public static final int IF = 22;
  public static final int DOT = 13;
  public static final int EOF = 0;
  public static final int RETURN = 44;
  public static final int EQUAL = 16;
  public static final int NEW = 35;
  public static final int error = 1;
  public static final int MUL = 33;
  public static final int COMA = 7;
  public static final int PLUSEQUAL = 40;
  public static final int NUMBER = 37;
  public static final int MOD = 31;
  public static final int BREAK = 4;
  public static final int IDENT = 21;
  public static final int VOID = 50;
  public static final int LBRACE = 24;
  public static final int ELSE = 14;
  public static final int LSQUARE = 28;
  public static final int READ = 43;
  public static final int RSQUARE = 47;
  public static final int MINUSEQUAL = 30;
  public static final int RBRACE = 45;
  public static final int PROG = 42;
  public static final int EXTENDS = 15;
  public static final int MODEQUAL = 32;
  public static final int MULEQUAL = 34;
  public static final int PRINT = 41;
}

